name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ak9761498165/ecommerce-api:latest .

      - name: Publish Image to Docker Hub
        run: docker push ak9761498165/ecommerce-api:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ak9761498165/ecommerce-api:latest

      - name: Delete old container
        run: docker rm -f ecommerce-ui-container || true  # Ignore error if the container doesn't exist

      - name: Run Docker Container
        run: |
          docker run -d -p 4000:4000 --name ecommerce-ui-container \
          -e DB_USER=abt \
          -e DB_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
          -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
          ak9761498165/ecommerce-api:latest
